### ISSUE TITLE
Enable webhook from Assistant - Only works if in Beta program

### ISSUE THREAD

**Issue by edzai** [IBM/watson-discovery-sdu-with-assistant#20]
Hi
I think you should explicitly say it from the beginning that to use this repo, set your services in Dallas and you have to be setup in Dallas for the "Enable webhook from Assistant" part to work.

I am stuck after creating the assistant and now when I go to "Options" I dont have the "Webhooks" tab.

**Comment by rhagarty** [comment]
@edzai - thanks for the heads-up. I was hoping it would have been released by now, so my apologies for the timing of this. I have been assured Assistant will be released very soon (week or so). In the meantime, I have updated the README and provided a link to get access to the beta program.

**Comment by edzai** [comment]
Thanks a mill

**Comment by edzai** [comment]
Hi, is it possible to add me to the beta program so I can test this app?

**Comment by rhagarty** [comment]
@edzai here is the link to use - https://cloud.ibm.com/docs/services/assistant?topic=assistant-feedback#feedback-beta
